name: Update Standings

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  build-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run standings fetch scripts
        run: |
          if [ -f tools/fetch_standings.py ]; then python tools/fetch_standings.py || exit 1; fi
          if [ -f tools/fetch_arca_standings.py ]; then python tools/fetch_arca_standings.py || exit 1; fi
          if [ -f tools/fetch_elite_standings.py ]; then python tools/fetch_elite_standings.py || exit 1; fi

      - name: Commit and push changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes in standings."
          else
            git config user.name "Standings Bot"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Auto update standings $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          fi
